#!/usr/bin/env node
/**
 * Regenerates src/data/glyphs.js from the SVG files in ../glyphs.
 *
 * Each built-in glyph is reduced to the two things the renderer needs: its
 * viewBox and the path data. Run this after editing a glyph:
 *
 *   node scripts/build-glyphs.mjs
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const uiDir = dirname(dirname(fileURLToPath(import.meta.url)));
const glyphDir = join(uiDir, '..', 'glyphs');
const NAMES = ['note', 'oriscus', 'quilisma', 'ascending', 'descending', 'strophicus'];

const glyphs = {};
for (const name of NAMES) {
    const file = join(glyphDir, `${name}.svg`);
    if (!existsSync(file)) {
        glyphs[name] = { viewBox: '0 0 10 10', d: 'M5,5 L10,10' };
        continue;
    }
    const svg = readFileSync(file, 'utf8');
    const viewBox = (svg.match(/viewBox="([^"]+)"/) || [])[1] || '0 0 10 10';
    const d = (svg.match(/ d="([^"]+)"/) || [])[1] || '';
    glyphs[name] = { viewBox, d };
}

const out = `// Generated by scripts/build-glyphs.mjs from ../glyphs/*.svg — do not edit.
export const GLYPHS = ${JSON.stringify(glyphs, null, 4)};
`;
writeFileSync(join(uiDir, 'src', 'data', 'glyphs.js'), out);
console.log(`Wrote src/data/glyphs.js (${NAMES.length} glyphs)`);
